language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - DJANGO=django==1.3
  - DJANGO=django==1.4
  - DJANGO=https://github.com/django/django/tarball/stable/1.5.x
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=django==1.3
    - python: "3.2"
      env: DJANGO=django==1.4
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install . --use-mirrors
script: python setup.py test
